# -*- Makefile -*-
#
# Tasmania
#
# Copyright (c) 2018-2019, ETH Zurich
# All rights reserved.
#
# This file is part of the Tasmania project. Tasmania is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or any later version. 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
PYSRC := $(shell find $(shell pwd) -name '*.py')
TMP_FILES := $(shell find $(shell pwd) -name '*.pyc')
TMP_FOLDERS := $(shell find $(shell pwd) -name '__pycache__') 
TMP_FOLDERS += $(shell find $(shell pwd) -name '.pytest_cache')
TMP_FOLDERS += $(shell find $(shell pwd) -name '.idea')
TMP_FOLDERS += $(shell find $(shell pwd) -name '.cache')
DOCDIR := doc
DOCSRC := $(DOCDIR)/source/conf.py $(DOCDIR)/source/api.rst
PARSERDIR := tasmania/grids/parser
UMLDIR := $(DOCDIR)/uml
TESTDIR := tests

all: clean parser html test

parser:
	@cd $(PARSERDIR) && $(MAKE)

html: parser
	@echo -n "Building HTML documentation ... "
	@cd $(DOCDIR) && $(MAKE) html > /dev/null 2>&1
	@echo "OK."

latex: parser
	@echo -n "Building LaTeX documentation ... "
	@cd $(DOCDIR) && $(MAKE) latex > /dev/null 2>&1
	@echo "OK."

latexpdf: parser
	@echo -n "Building LaTeX documentation ... "
	@cd $(DOCDIR) && $(MAKE) latexpdf > /dev/null
	@echo "OK."

uml: parser
	@echo -n "Building UML diagrams ... "
	@pyreverse -p grids -o eps grids/ > /dev/null
	@pyreverse -p dycore -f OTHER -o eps dycore/ > /dev/null
	@pyreverse -p storages -o eps storages/ > /dev/null
	@mv classes_*.eps $(UMLDIR) > /dev/null
	@mv packages_*.eps $(UMLDIR) > /dev/null
	@echo "OK."

test: parser
	@cd $(TESTDIR) && \
	 pytest --ignore=test_animation.py --ignore=test_contour_xz.py --ignore=test_contourf_xy.py \
			--ignore=test_contourf_xz.py --ignore=test_plot_grid.py --ignore=test_plot_overlapper.py \
			--ignore=test_plot_topography.py --ignore=test_profile_1d.py --ignore=test_quiver_xy.py \
			--ignore=test_subplots_assembler.py
	
.PHONY: clean gitignore

clean:
	@$(RM) $(TMP_FILES) > /dev/null
	@$(RM) -r $(TMP_FOLDERS) > /dev/null
	@find . -type f -name "*.sw[klmnop]" -delete
	@cd $(PARSERDIR) && $(MAKE) clean > /dev/null
	@cd $(PARSERDIR)/tests && $(MAKE) clean > /dev/null

gitignore:
	@sed -n '/# AUTOMATICALLY GENERATED TEXT/q;p' .gitignore | cat > .gitignore_tmp
	@cp .gitignore_tmp .gitignore
	@$(RM) .gitignore_tmp
	@echo '# AUTOMATICALLY GENERATED TEXT' 					  			>> .gitignore
	@echo '# The text after this comment and up to the end of file' 	>> .gitignore
	@echo '# has been automatically generated by the gitignore target'	>> .gitignore
	@echo '# of the makefile. To prevent this target from failing,'		>> .gitignore
	@echo '# no modifications should be applied by non-expert users.\n'	>> .gitignore
	@echo '# Files which exceed maximum size allowed by GitHub'			>> .gitignore 
	@find . -size +100M | cat >> .gitignore
	@echo '\n# END OF AUTOMATICALLY GENERATED TEXT'						>> .gitignore
