# Use Python3.6 runtime as parent image
FROM python:3.6.4-jessie

# Set the working directory to /tasmania
WORKDIR /tasmania

# Add docker folder to /tasmania
ADD . /tasmania/docker

# Install required Python packages specified in requirements.txt
RUN pip install -r /tasmania/docker/requirements.txt

# Install GT4Py dependencies
RUN apt-get update && \
	apt-get install -y chromium				\
					   cmake                \
                   	   libfreetype6-dev     \
                   	   libpng12-dev         \
					   graphviz				\
                   	   pkg-config           \
				   	   qt-sdk				\
				   	   vim					\
				   	   x11-apps				\
                	--no-install-recommends

# Install Boost-1.58.0
RUN wget -q -O boost_1_58_0.tar.gz 'http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.58.0%2F&ts=1446134333&use_mirror=kent' && \
	tar xvzf boost_1_58_0.tar.gz && \
	cd boost_1_58_0 && \
	./bootstrap.sh --with-libraries=timer,system,chrono --exec-prefix=/usr/local && \
	./b2 install && \
	cd .. && \
	rm -rf boost_1_58_0 boost_1_58_0.tar.gz

# Set matplotlib backend to Qt5
RUN cat /usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc | sed -e 's/^backend.*: TkAgg/backend : Qt5Agg/g' > /tmp/.matplotlibrc && \
	cp /tmp/.matplotlibrc /usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc

# Personalize bashrc configuration file
RUN cat /tasmania/docker/bashrc >> ~/.bashrc

# Set vimrc configuration file
RUN cp /tasmania/docker/vimrc ~/.vimrc

# Set useful environmental variables
ENV TERM xterm-256color
ENV QT_X11_NO_MITSHM 1
ENV CXX /usr/bin/g++                                					
ENV BOOST_ROOT /usr/local                           					
ENV TASMANIA_ROOT /tasmania            		 					
ENV GRIDTOOLS_ROOT /tasmania/gridtools 							
ENV LD_LIBRARY_PATH /usr/local/lib                  					
ENV PYTHONPATH ${PYTHONPATH}:/:/tasmania:/tasmania/gridtools
#ENV CUDATOOLKIT_HOME /usr/local/cuda-7.0            					
#ENV PATH $PATH:${CUDATOOLKIT_HOME}/bin            						
